server:
  port: 8083
  tomcat:
      max-threads: 1000
spring:
    datasource:
        url: jdbc:mysql:///stone?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
        # 使用druid 数据源
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        show-sql: true
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
spring.jpa.show-sql: true

spring.jpa.properties.hibernate.hbm2ddl.auto: update


spring.mvc.view.prefix: /*
spring.mvc.view.suffix: .jsp
  
  
  
  